require:
  - 'rubocop-performance'
  - 'rubocop-rails'
  - 'rubocop-rspec'

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
  TargetRailsVersion: 7.0
  TargetRubyVersion: 3.1.0

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Max: 40

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Style/HashSyntax:
  EnforcedShorthandSyntax: never
